In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns 
import plotly.express as px 
import plotly.graph_objects as go
from pathlib import Path
import geopandas as gps
import matplotlib.pyplot as plt
import os

In [2]:
df = pd.read_excel("dados.xlsx", sheet_name = "Dados")
df["data"] = pd.to_datetime(df["data"], dayfirst=True, errors = "coerce", format = "mixed")
df.to_csv("dados.csv", index = False)

In [5]:
dados = pd.read_csv("dados.csv")
pd.to_datetime(dados["data"])
dados["dia_semana"].unique()

<StringArray>
['ter', 'qua', 'qui', 'sex', 'sáb', 'seg', 'dom']
Length: 7, dtype: str

In [ ]:
teste = df.groupby(["data","setor","turno"], as_index = False).aggregate(peso = ("producao", "sum"), dia_semana = ("dia_semana", "unique"))
teste["dia_semana"] = [i[0] for i in teste["dia_semana"]]
teste["data"] = pd.to_datetime(teste["data"], dayfirst= True)
teste = teste[(teste["data"]>="20/05/2025") & (teste["data"]<="20/06/2025") & (teste["dia_semana"].isin(["seg","qua","sex"]))]
px.line(teste, x = "data", y = "peso", color = "setor")

In [4]:
def serie_historica(dados, data_ini, data_fin, dia_sem ,turn ,var):
    teste = dados
    teste["data"] = pd.to_datetime(teste["data"], dayfirst= True)
    teste = dados.groupby(["data", "setor", "turno"], as_index = False).aggregate(var = (var,"sum"), dia_semana = ("dia_semana", "unique"))
    teste["dia_semana"] = [i[0] for i in teste["dia_semana"]]
    teste = teste[(teste["data"]>=data_ini) & (teste["data"]<=data_fin) & (teste["turno"].isin(turn)) & (teste["dia_semana"].isin(dia_sem))]
    
    teste.sort_values(by = "data", inplace = True)
    teste["indexes"] = teste["data"].dt.strftime("%d/%m/%y") + "<br>" + teste["dia_semana"]
    
    figura = px.line(teste, x = "indexes", y = "var", color = "setor")
    figura.show()
    
    return teste

In [ ]:
treino  = serie_historica(df, "20/05/2025", "20/10/2025", ["seg","qua","sex"], ["DIURNO"] ,"horas_coleta")

In [6]:
def medias(dados, data_ini, data_fin, dia_sem ,turn ,var):
    teste = dados
    teste["data"] = pd.to_datetime(teste["data"], dayfirst= True)
    
    teste = teste[(teste["data"] >= data_ini) & (teste["data"] <= data_fin) & (teste["turno"].isin(turn)) & (teste["dia_semana"].isin(dia_sem))].copy()
    
    teste = teste.groupby(["setor", "dia_semana" ,"turno"], as_index= False)[var].mean()
    
    figura = px.bar(teste, x = var, y = "setor", color = "dia_semana", orientation= "h")
    figura.update_layout(barmode = "group")
    figura.show()

In [ ]:
medias(df, "20/05/2025", "20/06/2025",["seg","qua","sex"], ["DIURNO"], "producao")

In [ ]:
!pip install geopandas

In [9]:
mapa_atual = gps.read_file("Novos/01.shp")

for i in range(2,22):
    if i <10: 
        mapa = gps.read_file(f"Novos/0{i}.shp")
        mapa_atual = pd.concat([mapa_atual, mapa])
    else:
        mapa = gps.read_file(f"Novos/{i}.shp")
        mapa_atual = pd.concat([mapa_atual, mapa])

In [10]:
mapa_atual

,IDENTIFICA,SETOR,APELIDO,MACROSETOR,COR,FREQUENCIA,geometry
0,00101,01,01,RIO CLARO - DOMICILIAR,0.0,"TER, QUI E SAB - NOTURNO","POLYGON ((-47.57459 -22.39923, -47.57378 -22.3..."
0,00102,02,02,RIO CLARO - DOMICILIAR,0.0,"TER, QUI E SAB - NOTURNO","POLYGON ((-47.57533 -22.4002, -47.57422 -22.40..."
0,00103,03,03,RIO CLARO - DOMICILIAR,0.0,"SEG, QUA E SEX - NOTURNO","POLYGON ((-47.55478 -22.42679, -47.55476 -22.4..."
0,00104,04,04,RIO CLARO - DOMICILIAR,0.0,"SEG, QUA E SEX - NOTURNO","POLYGON ((-47.5519 -22.40962, -47.5511 -22.407..."
0,00105,05,05,RIO CLARO - DOMICILIAR,0.0,"SEG, QUA E SEX - NOTURNO","POLYGON ((-47.54898 -22.3847, -47.5483 -22.385..."
0,00106,06,06,RIO CLARO - DOMICILIAR,0.0,"TER, QUI E SAB - NOTURNO","POLYGON ((-47.53722 -22.39061, -47.54301 -22.4..."
0,00107,07,07,RIO CLARO - DOMICILIAR,0.0,"SEG, QUA E SEX - NOTURNO","POLYGON ((-47.5608 -22.3949, -47.56202 -22.395..."
0,00108,08,08,RIO CLARO - DOMICILIAR,0.0,"TER, QUI E SAB - DIURNO","POLYGON ((-47.5746 -22.39257, -47.5737 -22.394..."
0,00109,09,09,RIO CLARO - DOMICILIAR,0.0,"SEG, QUA E SEX - DIURNO","POLYGON ((-47.58637 -22.39358, -47.58442 -22.3..."
0,00110,10,10,RIO CLARO - DOMICILIAR,0.0,"TER, QUI E SAB - DIURNO","POLYGON ((-47.58308 -22.41944, -47.58277 -22.4..."
0,00111,11,11,RIO CLARO - DOMICILIAR,0.0,"TER, QUI E SAB - NOTURNO","POLYGON ((-47.5685 -22.43317, -47.569 -22.4338..."
0,00112,12,12,RIO CLARO - DOMICILIAR,0.0,"TER, QUI E SAB - DIURNO","POLYGON ((-47.56412 -22.37586, -47.56379 -22.3..."
0,00113,13,13,RIO CLARO - DOMICILIAR,0.0,"SEG, QUA E SEX - DIURNO","POLYGON ((-47.54688 -22.3803, -47.54734 -22.38..."
0,00114,14,14,RIO CLARO - DOMICILIAR,0.0,"SEG, QUA E SEX - DIURNO","POLYGON ((-47.53584 -22.38387, -47.53817 -22.3..."
0,00115,15,15,RIO CLARO - DOMICILIAR,0.0,"TER, QUI E SAB - DIURNO","POLYGON ((-47.60129 -22.43654, -47.60144 -22.4..."
0,00116,16,16,RIO CLARO - DOMICILIAR,0.0,"SEG, QUA E SEX - DIURNO","POLYGON ((-47.57313 -22.38729, -47.57642 -22.3..."
0,00117,17,17,RIO CLARO - DOMICILIAR,0.0,"TER, QUI E SAB - DIURNO","POLYGON ((-47.56828 -22.4442, -47.57027 -22.44..."
0,00118,18,18,RIO CLARO - DOMICILIAR,0.0,"SEG, QUA E SEX - DIURNO","POLYGON ((-47.58473 -22.25624, -47.57843 -22.2..."
0,00119,19,19,RIO CLARO - DOMICILIAR,0.0,"TER, QUI E SAB - DIURNO","POLYGON ((-47.60932 -22.38414, -47.60508 -22.3..."
0,00120,20,20,RIO CLARO - DOMICILIAR,0.0,"SEG, QUA E SEX - DIURNO","POLYGON ((-47.54236 -22.38368, -47.54227 -22.3..."
0,00121,21,21,RIO CLARO - DOMICILIAR,0.0,"SEG, TER, QUA, QUI, SEX, SAB - NOTURNO","POLYGON ((-47.5553 -22.41693, -47.55666 -22.41..."

In [11]:
mapa_atual = mapa_atual.to_crs(epsg=4326)

mapa_atual.to_file("mapa_read.geojson", driver = "GeoJSON")

In [8]:
mapa_atual = gps.read_file("mapa_atual.geojson")
df = pd.read_excel("dados.xlsx",sheet_name = "Dados")
teste = df.groupby( "setor", as_index = False)["producao"].mean()
teste.drop([21, 22], axis = 0, inplace = True)
teste["setor"] = [f"0{i}" if i < 10 else f"{i}" for i in teste["setor"]]

In [12]:
mapa

{'type': 'FeatureCollection',
 'features': [{'id': '0',
   'type': 'Feature',
   'properties': {'IDENTIFICA': '00101',
    'SETOR': '01',
    'APELIDO': '01',
    'MACROSETOR': 'RIO CLARO - DOMICILIAR',
    'COR': 3328050.0,
    'FREQUENCIA': 'TER/QUI/SAB - NOTURNO'},
   'geometry': {'type': 'Polygon',
    'coordinates': (((-47.563047, -22.395606),
      (-47.563029, -22.395806),
      (-47.563021, -22.396073),
      (-47.563149, -22.39713),
      (-47.563353, -22.398674),
      (-47.563492, -22.399212),
      (-47.563735, -22.399632),
      (-47.563744, -22.399647),
      (-47.563806, -22.399753),
      (-47.563875, -22.399873),
      (-47.56396, -22.400022),
      (-47.564137, -22.400306),
      (-47.564212, -22.40046),
      (-47.564252, -22.400541),
      (-47.564352, -22.400748),
      (-47.564448, -22.400946),
      (-47.564535, -22.401124),
      (-47.564661, -22.401418),
      (-47.564801, -22.401746),
      (-47.564903, -22.401984),
      (-47.564987, -22.40238),
      (-47.565125, -22.403036),
      (-47.565141, -22.403148),
      (-47.565234, -22.403831),
      (-47.565179, -22.404784),
      (-47.565069, -22.405224),
      (-47.56486, -22.405693),
      (-47.564463, -22.406517),
      (-47.564862, -22.408472),
      (-47.565905, -22.409688),
      (-47.56673, -22.410776),
      (-47.567598, -22.411225),
      (-47.568496, -22.412105),
      (-47.569772, -22.413397),
      (-47.569863, -22.413497),
      (-47.569866, -22.413492),
      (-47.569868, -22.413487),
      (-47.569871, -22.413479),
      (-47.570741, -22.411426),
      (-47.571687, -22.409221),
      (-47.572739, -22.406601),
      (-47.574221, -22.40304),
      (-47.575334, -22.400198),
      (-47.575406, -22.400053),
      (-47.575404, -22.400053),
      (-47.575391, -22.400054),
      (-47.574944, -22.400093),
      (-47.574821, -22.399615),
      (-47.574517, -22.399377),
      (-47.574521, -22.39937),
      (-47.574546, -22.399327),
      (-47.574545, -22.399327),
      (-47.573594, -22.399026),
      (-47.572824, -22.398797),
      (-47.572884, -22.398655),
      (-47.571828, -22.398322),
      (-47.570988, -22.398056),
      (-47.569618, -22.397609),
      (-47.569176, -22.397465),
      (-47.567798, -22.397036),
      (-47.566948, -22.396788),
      (-47.566685, -22.396712),
      (-47.566519, -22.396656),
      (-47.5656, -22.396351),
      (-47.564425, -22.39602),
      (-47.564425, -22.39602),
      (-47.564272, -22.395976),
      (-47.564211, -22.395955),
      (-47.563051, -22.395555),
      (-47.563047, -22.395606)),)},
   'bbox': (-47.575406, -22.413497, -47.563021, -22.395555)},
  {'id': '1',
   'type': 'Feature',
   'properties': {'IDENTIFICA': '00102',
    'SETOR': '02',
    'APELIDO': '02',
    'MACROSETOR': 'RIO CLARO - DOMICILIAR',
    'COR': 3328050.0,
    'FREQUENCIA': 'TER/QUI/SAB - NOTURNO'},
   'geometry': {'type': 'Polygon',
    'coordinates': (((-47.575334, -22.400198),
      (-47.574221, -22.40304),
      (-47.572739, -22.406601),
      (-47.571687, -22.409221),
      (-47.570741, -22.411426),
      (-47.569871, -22.413479),
      (-47.569868, -22.413487),
      (-47.569866, -22.413492),
      (-47.569863, -22.413497),
      (-47.56996, -22.413647),
      (-47.569139, -22.4158),
      (-47.568803, -22.416498),
      (-47.568829, -22.416507),
      (-47.572258, -22.417674),
      (-47.574023, -22.418297),
      (-47.575768, -22.418892),
      (-47.575791, -22.4189),
      (-47.576594, -22.419222),
      (-47.576843, -22.41969),
      (-47.577634, -22.419878),
      (-47.577647, -22.419881),
      (-47.578041, -22.419101),
      (-47.578158, -22.41887),
      (-47.57914, -22.41709),
      (-47.582473, -22.412765),
      (-47.583063, -22.412086),
      (-47.58861, -22.405577),
      (-47.588594, -22.405578),
      (-47.585888, -22.405792),
      (-47.583915, -22.406014),
      (-47.583916, -22.406013),
      (-47.583994, -22.404134),
      (-47.584113, -22.401391),
      (-47.58341, -22.400694),
      (-47.583398, -22.400697),
      (-47.582961, -22.400801),
      (-47.58244, -22.400871),
      (-47.582428, -22.400871),
      (-47.581055, -22.400832),
      (-47.579866, -22.400741),
      (-47.579455, -22.400642),
      (-47.579211, -22.400557),
      (-47.577795, -22.40007),
      (-47.575406, -22.400053),
      (-47.575406, -22.400053),
      (-47.575334, -22.400198)),)},
   'bbox': (-47.58861, -22.419881, -47.568803, -22.400053)},
  {'id': '2',
   'type': 'Feature',
   'properties': {'IDENTIFICA': '00103',
    'SETOR': '03',
    'APELIDO': '03',
    'MACROSETOR': 'RIO CLARO - DOMICILIAR',
    'COR': 13132850.0,
    'FREQUENCIA': 'SEG/QUA/SEX - NOTURNO'},
   'geometry': {'type': 'Polygon',
    'coordinates': (((-47.552897, -22.416486),
      (-47.552647, -22.417899),
      (-47.552142, -22.419763),
      (-47.551846, -22.421223),
      (-47.551456, -22.423081),
      (-47.551894, -22.424241),
      (-47.55274, -22.425405),
      (-47.553745, -22.426975),
      (-47.554011, -22.428504),
      (-47.553857, -22.429718),
      (-47.553596, -22.430843),
      (-47.553513, -22.432706),
      (-47.554155, -22.434828),
      (-47.554586, -22.43645),
      (-47.555401, -22.438687),
      (-47.557567, -22.439977),
      (-47.559041, -22.437812),
      (-47.560285, -22.436061),
      (-47.561658, -22.434607),
      (-47.562819, -22.433941),
      (-47.562174, -22.432328),
      (-47.563141, -22.428763),
      (-47.564409, -22.427224),
      (-47.567043, -22.420775),
      (-47.567037, -22.420773),
      (-47.565216, -22.420164),
      (-47.564499, -22.419939),
      (-47.564083, -22.419803),
      (-47.563515, -22.419576),
      (-47.563123, -22.41943),
      (-47.56283, -22.419335),
      (-47.562481, -22.419234),
      (-47.561333, -22.418868),
      (-47.560425, -22.418583),
      (-47.55879, -22.418044),
      (-47.558127, -22.417843),
      (-47.557083, -22.417494),
      (-47.55666, -22.417373),
      (-47.555333, -22.416915),
      (-47.555326, -22.416915),
      (-47.555326, -22.416915),
      (-47.552897, -22.416486)),)},
   'bbox': (-47.567043, -22.439977, -47.551456, -22.416486)},
  {'id': '3',
   'type': 'Feature',
   'properties': {'IDENTIFICA': '00104',
    'SETOR': '04',
    'APELIDO': '04',
    'MACROSETOR': 'RIO CLARO - DOMICILIAR',
    'COR': 13132850.0,
    'FREQUENCIA': 'SEG/QUA/SEX - NOTURNO'},
   'geometry': {'type': 'Polygon',
    'coordinates': (((-47.551908, -22.403979),
      (-47.551268, -22.406082),
      (-47.551284, -22.40624),
      (-47.551283, -22.406327),
      (-47.551275, -22.406406),
      (-47.551267, -22.406472),
      (-47.551242, -22.40653),
      (-47.551212, -22.406596),
      (-47.551081, -22.406801),
      (-47.549522, -22.40683),
      (-47.548031, -22.406873),
      (-47.54689, -22.407165),
      (-47.544432, -22.407965),
      (-47.543013, -22.408498),
      (-47.542999, -22.409788),
      (-47.54444, -22.411276),
      (-47.545544, -22.413677),
      (-47.542567, -22.424926),
      (-47.536853, -22.429199),
      (-47.537621, -22.433377),
      (-47.539062, -22.43621),
      (-47.539974, -22.438083),
      (-47.541354, -22.439061),
      (-47.542097, -22.439835),
      (-47.542823, -22.440892),
      (-47.543642, -22.442489),
      (-47.544632, -22.444127),
      (-47.545634, -22.446104),
      (-47.546937, -22.446102),
      (-47.549914, -22.444085),
      (-47.552363, -22.442404),
      (-47.554586, -22.43645),
      (-47.554155, -22.434828),
      (-47.553513, -22.432706),
      (-47.553596, -22.430843),
      (-47.553857, -22.429718),
      (-47.554011, -22.428504),
      (-47.553745, -22.426975),
      (-47.55274, -22.425405),
      (-47.551894, -22.424241),
      (-47.551456, -22.423081),
      (-47.551846, -22.421223),
      (-47.552142, -22.419763),
      (-47.552647, -22.417899),
      (-47.552897, -22.416486),
      (-47.553536, -22.414938),
      (-47.554608, -22.413751),
      (-47.556823, -22.412043),
      (-47.557314, -22.410991),
      (-47.558468, -22.407819),
      (-47.558619, -22.405591),
      (-47.558619, -22.405579),
      (-47.558619, -22.405578),
      (-47.556569, -22.404941),
      (-47.556531, -22.40516),
      (-47.554649, -22.404617),
      (-47.552408, -22.403972),
      (-47.552326, -22.404042),
      (-47.552218, -22.404088),
      (-47.552077, -22.404093),
      (-47.55198, -22.404056),
      (-47.551908, -22.403979)),)},
   'bbox': (-47.558619, -22.446104, -47.536853, -22.403972)},
  {'id': '4',
   'type': 'Feature',
   'properties': {'IDENTIFICA': '00105',
    'SETOR': '05',
    'APELIDO': '05',
    'MACROSETOR': 'RIO CLARO - DOMICILIAR',
    'COR': 13132850.0,
    'FREQUENCIA': 'SEG/QUA/SEX - NOTURNO'},
   'geometry': {'type': 'Polygon',
    'coordinates': (((-47.548974, -22.384665),
      (-47.548339, -22.385085),
      (-47.548025, -22.384689),
      (-47.547945, -22.3846),
      (-47.547827, -22.384552),
      (-47.547471, -22.384067),
      (-47.546643, -22.384335),
      (-47.544704, -22.384883),
      (-47.54361, -22.385183),
      (-47.542411, -22.386055),
      (-47.542353, -22.386557),
      (-47.542194, -22.386736),
      (-47.542256, -22.387759),
      (-47.542564, -22.388419),
      (-47.543022, -22.388822),
      (-47.544551, -22.389676),
      (-47.545943, -22.390417),
      (-47.547376, -22.392043),
      (-47.550102, -22.395434),
      (-47.550134, -22.395473),
      (-47.553669, -22.394458),
      (-47.556426, -22.393738),
      (-47.556473, -22.393726),
      (-47.556738, -22.394552),
      (-47.557569, -22.394509),
      (-47.558397, -22.394534),
      (-47.559271, -22.394437),
      (-47.559389, -22.394848),
      (-47.560059, -22.394762),
      (-47.559961, -22.394483),
      (-47.558611, -22.388991),
      (-47.55788, -22.385805),
      (-47.557045, -22.385974),
      (-47.555756, -22.386257),
      (-47.555093, -22.386394),
      (-47.553357, -22.386776),
      (-47.552035, -22.385278),
      (-47.550473, -22.383597),
      (-47.548974, -22.384665)),)},
   'bbox': (-47.560059, -22.395473, -47.542194, -22.383597)},
  {'id': '5',
   'type': 'Feature',
   'properties': {'IDENTIFICA': '00106',
    'SETOR': '06',
    'APELIDO': '06',
    'MACROSETOR': 'RIO CLARO - DOMICILIAR',
    'COR': 3328050.0,
    'FREQUENCIA': 'TER/QUI/SAB - NOTURNO'},
   'geometry': {'type': 'Polygon',
    'coordinates': (((-47.537227, -22.390612),
      (-47.543013, -22.408498),
      (-47.544432, -22.407965),
      (-47.54689, -22.407165),
      (-47.548031, -22.406873),
      (-47.549522, -22.40683),
      (-47.551081, -22.406801),
      (-47.551212, -22.406596),
      (-47.551242, -22.40653),
      (-47.551267, -22.406472),
      (-47.551275, -22.406406),
      (-47.551283, -22.406327),
      (-47.551284, -22.40624),
      (-47.551268, -22.406082),
      (-47.551908, -22.403979),
      (-47.55198, -22.404056),
      (-47.552077, -22.404093),
      (-47.552218, -22.404088),
      (-47.552326, -22.404042),
      (-47.552408, -22.403972),
      (-47.554649, -22.404617),
      (-47.556531, -22.40516),
      (-47.556569, -22.404941),
      (-47.558619, -22.405578),
      (-47.558603, -22.404967),
      (-47.558603, -22.404963),
      (-47.558624, -22.404458),
      (-47.559195, -22.402688),
      (-47.559825, -22.400256),
      (-47.559822, -22.400253),
      (-47.559416, -22.399728),
      (-47.559417, -22.399717),
      (-47.55944, -22.39908),
      (-47.559674, -22.398439),
      (-47.559705, -22.398352),
      (-47.561756, -22.398982),
      (-47.563717, -22.399638),
      (-47.563744, -22.399647),
      (-47.563735, -22.399632),
      (-47.563492, -22.399212),
      (-47.563353, -22.398674),
      (-47.563149, -22.39713),
      (-47.563021, -22.396073),
      (-47.563029, -22.395806),
      (-47.563047, -22.395606),
      (-47.563032, -22.395601),
      (-47.562971, -22.395582),
      (-47.56211, -22.395304),
      (-47.562045, -22.395285),
      (-47.560763, -22.394922),
      (-47.560094, -22.394862),
      (-47.560059, -22.394762),
      (-47.559389, -22.394848),
      (-47.559271, -22.394437),
      (-47.558397, -22.394534),
      (-47.557569, -22.394509),
      (-47.556738, -22.394552),
      (-47.556473, -22.393726),
      (-47.556426, -22.393738),
      (-47.553669, -22.394458),
      (-47.550134, -22.395473),
      (-47.550102, -22.395434),
      (-47.547376, -22.392043),
      (-47.545943, -22.390417),
      (-47.544551, -22.389676),
      (-47.543022, -22.388822),
      (-47.542564, -22.388419),
      (-47.542256, -22.387759),
      (-47.542194, -22.386736),
      (-47.54214, -22.386816),
      (-47.541924, -22.387133),
      (-47.540248, -22.388698),
      (-47.540189, -22.388735),
      (-47.537227, -22.390612)),)},
   'bbox': (-47.563744, -22.408498, -47.537227, -22.386736)},
  {'id': '6',
   'type': 'Feature',
   'properties': {'IDENTIFICA': '00107',
    'SETOR': '07',
    'APELIDO': '07',
    'MACROSETOR': 'RIO CLARO - DOMICILIAR',
    'COR': 13132850.0,
    'FREQUENCIA': 'SEG/QUA/SEX - NOTURNO'},
   'geometry': {'type': 'Polygon',
    'coordinates': (((-47.560763, -22.394922),
      (-47.562045, -22.395285),
      (-47.56211, -22.395304),
      (-47.562971, -22.395582),
      (-47.563032, -22.395601),
      (-47.563047, -22.395606),
      (-47.563051, -22.395555),
      (-47.564211, -22.395955),
      (-47.564272, -22.395976),
      (-47.564425, -22.39602),
      (-47.564425, -22.39602),
      (-47.5656, -22.396351),
      (-47.566519, -22.396656),
      (-47.566685, -22.396712),
      (-47.566948, -22.396788),
      (-47.567798, -22.397036),
      (-47.569176, -22.397465),
      (-47.569618, -22.397609),
      (-47.570988, -22.398056),
      (-47.571828, -22.398322),
      (-47.572884, -22.398655),
      (-47.574617, -22.394561),
      (-47.573714, -22.394759),
      (-47.574605, -22.392573),
      (-47.575515, -22.390575),
      (-47.576423, -22.388492),
      (-47.573131, -22.387288),
      (-47.572303, -22.387062),
      (-47.571691, -22.386934),
      (-47.566365, -22.386942),
      (-47.564832, -22.386894),
      (-47.563292, -22.386845),
      (-47.562966, -22.386724),
      (-47.561803, -22.38635),
      (-47.562012, -22.384978),
      (-47.558018, -22.385796),
      (-47.558611, -22.388991),
      (-47.559961, -22.394483),
      (-47.560059, -22.394762),
      (-47.560094, -22.394862),
      (-47.560763, -22.394922)),)},
   'bbox': (-47.576423, -22.398655, -47.558018, -22.384978)},
  {'id': '7',
   'type': 'Feature',
   'properties': {'IDENTIFICA': '00108',
    'SETOR': '08',
    'APELIDO': '08',
    'MACROSETOR': 'RIO CLARO - DOMICILIAR',
    'COR': 15470094.0,
    'FREQUENCIA': 'TER/QUI/SAB - DIURNO'},
   'geometry': {'type': 'MultiPolygon',
    'coordinates': [(((-47.574605, -22.392573),
       (-47.573714, -22.394759),
       (-47.574617, -22.394561),
       (-47.57616, -22.394204),
       (-47.578021, -22.393817),
       (-47.578257, -22.393839),
       (-47.578363, -22.394117),
       (-47.577788, -22.39518),
       (-47.580821, -22.396264),
       (-47.584503, -22.397962),
       (-47.586369, -22.393578),
       (-47.585847, -22.393422),
       (-47.586636, -22.391564),
       (-47.585878, -22.391313),
       (-47.586267, -22.390409),
       (-47.58591, -22.390266),
       (-47.584358, -22.389758),
       (-47.58204, -22.388968),
       (-47.582709, -22.387985),
       (-47.58317, -22.387194),
       (-47.584241, -22.385682),
       (-47.585976, -22.383412),
       (-47.585871, -22.383427),
       (-47.583318, -22.383795),
       (-47.58026, -22.384295),
       (-47.579228, -22.384671),
       (-47.57842, -22.385398),
       (-47.577818, -22.385864),
       (-47.577315, -22.386394),
       (-47.576947, -22.387238),
       (-47.576423, -22.388492),
       (-47.575515, -22.390575),
       (-47.574605, -22.392573)),),
     (((-47.570828, -22.374671),
       (-47.568119, -22.379105),
       (-47.569369, -22.37888),
       (-47.57131, -22.379191),
       (-47.572118, -22.379172),
       (-47.571923, -22.37962),
       (-47.570864, -22.380805),
       (-47.571348, -22.381217),
       (-47.572825, -22.381958),
       (-47.574418, -22.38268),
       (-47.575223, -22.38095),
       (-47.576451, -22.378455),
       (-47.57678, -22.377995),
       (-47.57758, -22.377455),
       (-47.576715, -22.376637),
       (-47.576238, -22.376554),
       (-47.574329, -22.375755),
       (-47.573172, -22.374661),
       (-47.571388, -22.373637),
       (-47.570828, -22.374671)),)]},
   'bbox': (-47.586636, -22.397962, -47.568119, -22.373637)},
  {'id': '8',
   'type': 'Feature',
   'properties': {'IDENTIFICA': '00109',
    'SETOR': '09',
    'APELIDO': '09',
    'MACROSETOR': 'RIO CLARO - DOMICILIAR',
    'COR': 15470094.0,
    'FREQUENCIA': 'SEG/QUA/SEX - DIURNO'},
   'geometry': {'type': 'Polygon',
    'coordinates': (((-47.586369, -22.393578),
      (-47.584503, -22.397962),
      (-47.580821, -22.396264),
      (-47.580144, -22.398127),
      (-47.579211, -22.400557),
      (-47.579455, -22.400642),
      (-47.579866, -22.400741),
      (-47.581055, -22.400832),
      (-47.582428, -22.400871),
      (-47.58244, -22.400871),
      (-47.582961, -22.400801),
      (-47.583398, -22.400697),
      (-47.58341, -22.400694),
      (-47.584113, -22.401391),
      (-47.583994, -22.404134),
      (-47.583916, -22.406013),
      (-47.583915, -22.406014),
      (-47.585888, -22.405792),
      (-47.588594, -22.405578),
      (-47.58861, -22.405577),
      (-47.596946, -22.395989),
      (-47.595086, -22.395154),
      (-47.595293, -22.393979),
      (-47.596814, -22.392574),
      (-47.596077, -22.389694),
      (-47.59481, -22.388427),
      (-47.594188, -22.387966),
      (-47.593612, -22.386192),
      (-47.59276, -22.384892),
      (-47.590926, -22.384058),
      (-47.589926, -22.383225),
      (-47.588516, -22.382959),
      (-47.586331, -22.383312),
      (-47.585976, -22.383412),
      (-47.584241, -22.385682),
      (-47.58317, -22.387194),
      (-47.582709, -22.387985),
      (-47.58204, -22.388968),
      (-47.584358, -22.389758),
      (-47.58591, -22.390266),
      (-47.586267, -22.390409),
      (-47.585878, -22.391313),
      (-47.586636, -22.391564),
      (-47.585847, -22.393422),
      (-47.586369, -22.393578)),)},
   'bbox': (-47.596946, -22.406014, -47.579211, -22.382959)},
  {'id': '9',
   'type': 'Feature',
   'properties': {'IDENTIFICA': '00110',
    'SETOR': '10',
    'APELIDO': '10',
    'MACROSETOR': 'RIO CLARO - DOMICILIAR',
    'COR': 6566500.0,
    'FREQUENCIA': 'TER/QUI/SAB - DIURNO'},
   'geometry': {'type': 'MultiPolygon',
    'coordinates': [(((-47.583192, -22.418599),
       (-47.583078, -22.419438),
       (-47.582773, -22.419361),
       (-47.582086, -22.419142),
       (-47.581311, -22.419062),
       (-47.58086, -22.419039),
       (-47.58002, -22.418986),
       (-47.57933, -22.419),
       (-47.578041, -22.419101),
       (-47.577647, -22.419881),
       (-47.57664, -22.421909),
       (-47.575191, -22.424688),
       (-47.572898, -22.429244),
       (-47.572028, -22.430905),
       (-47.570894, -22.433422),
       (-47.576919, -22.434914),
       (-47.58045, -22.435579),
       (-47.58209, -22.435813),
       (-47.582136, -22.435438),
       (-47.582177, -22.434818),
       (-47.582238, -22.434062),
       (-47.582316, -22.433138),
       (-47.582138, -22.432502),
       (-47.581539, -22.430749),
       (-47.581198, -22.42977),
       (-47.580369, -22.42786),
       (-47.582013, -22.425515),
       (-47.583562, -22.423252),
       (-47.586071, -22.424402),
       (-47.587944, -22.425019),
       (-47.589649, -22.427086),
       (-47.590287, -22.425469),
       (-47.59034, -22.424023),
       (-47.588082, -22.421765),
       (-47.584782, -22.421195),
       (-47.58706, -22.417859),
       (-47.585914, -22.416859),
       (-47.585815, -22.415469),
       (-47.584985, -22.41497),
       (-47.584619, -22.414634),
       (-47.584509, -22.414609),
       (-47.584209, -22.41482),
       (-47.583591, -22.416973),
       (-47.583192, -22.418599)),),
     (((-47.574821, -22.399615),
       (-47.574944, -22.400093),

In [11]:
mapa = mapa_atual.__geo_interface__

In [ ]:
fig = px.choropleth(teste, geojson=mapa, locations="setor", featureidkey="properties.SETOR", color="producao", color_continuous_scale="Oranges")
fig.update_layout(width=500,height=700, margin = dict(l=4, r=0, t=0, b=0), coloraxis_colorbar=dict(len=0.6))
fig.update_geos(projection_type="mercator", fitbounds = "geojson", visible = False, domain=dict(x=[0, 1], y=[0, 1]), projection_scale = 1 )
fig.show()

In [ ]:
fig = px.choropleth_map(
    teste,
    geojson=mapa,
    locations="setor",
    featureidkey="properties.SETOR",
    color="producao",
    color_continuous_scale="Oranges",
    center = {"lat": -22.39, "lon": -47.577}, 
    zoom = 11)

fig.update_layout(
    margin=dict(l=8, r=0, t=0, b=0), 
    width = 500, 
    height = 900)

fig.update_traces(marker=dict(opacity=0.5))

In [29]:
def mapa_analitico(variavel, data_ini, data_fin, turno, dia_semana):
    
    #importação dos dados
    url = "https://raw.githubusercontent.com/Schummy07/monitoramento/main/dados.csv"
    dados = pd.read_csv(url)
    dados["data"] = pd.to_datetime(dados["data"])
    
    
    url_mapa = "https://raw.githubusercontent.com/Schummy07/monitoramento/refs/heads/main/mapa_atual.geojson"
    mapa = gps.read_file(url_mapa)
    
    
    #aplicação dos filtros 
    dados_analise = dados[(dados["data"]>= data_ini) &
                          (dados["data"]<= data_fin) &
                          (dados["turno"].isin(turno)) &
                          (dados["dia_semana"].isin(dia_semana))]
    
    #calculo das médias da variável selecionada para cada setor 
    medias = dados_analise.groupby("setor", as_index = False)[variavel].mean()
    medias["setor"] = [f"0{i}" if i <10 else f"{i}" for i in medias["setor"]]
    
    #aplicação do filtro no arquivo shp 
    mapa_filtro = mapa[mapa["SETOR"].isin(medias["setor"])]
    mapa_plot = mapa_filtro.__geo_interface__
    
    # return mapa_filtro, medias - linha de teste 
    # plot do gráfico georeferenciado 
    fig = px.choropleth_map(
        medias,
        geojson=mapa_plot,
        locations="setor",
        featureidkey="properties.SETOR",
        color= variavel,
        color_continuous_scale="Oranges",
        center = {"lat": -22.39, "lon": -47.577}, 
        zoom = 11, 
        opacity = 0.5)
    
    fig.update_layout(
        margin=dict(l=8, r=0, t=0, b=0), 
        width = 500, 
        height = 900)
    
    fig.show()

In [30]:
mapa_analitico("producao", "20/05/2025", "20/06/2025", ["DIURNO"], ["seg","qua"])

In [106]:
df[df["dia_semana"]=="sáb"]

,data,mês,dia_mes,dia_semana,setor,turno,carro,tempo_coleta,horas_coleta,tempo_trajeto,horas_trajeto,tempo_aterro,horas_aterro,km_coleta,km_trajeto,producao,producao_ton,viagens,ton/h,ton/km
47,2025-04-05,abr,5,sáb,8,DIURNO,31912,07:34:00,7.566667,01:50:00,1.833333,00:20:00,0.333333,34,46,14270,14.27,2,1.885903,0.419706
48,2025-04-05,abr,5,sáb,10,DIURNO,33049,04:23:00,4.383333,00:27:00,0.450000,00:25:00,0.416667,36,16,12190,12.19,1,2.780989,0.338611
49,2025-04-05,abr,5,sáb,12,DIURNO,32049,07:30:00,7.500000,01:23:00,1.383333,00:45:00,0.750000,37,51,15350,15.35,2,2.046667,0.414865
50,2025-04-05,abr,5,sáb,15,DIURNO,32048,05:00:00,5.000000,01:00:00,1.000000,00:15:00,0.250000,40,19,13990,13.99,2,2.798000,0.349750
51,2025-04-05,abr,5,sáb,17,DIURNO,33049,05:50:00,5.833333,00:50:00,0.833333,00:15:00,0.250000,48,15,16010,16.01,2,2.744571,0.333542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2905,2026-01-03,jan,3,sáb,6,NOTURNO,33049,03:52:00,3.866667,00:54:00,0.900000,00:12:00,0.200000,21,21,11560,11.56,1,2.989655,0.550476
2906,2026-01-03,jan,3,sáb,11,NOTURNO,32051,02:50:00,2.833333,00:25:00,0.416667,00:15:00,0.250000,12,12,9030,9.03,1,3.187059,0.752500
2907,2026-01-03,jan,3,sáb,11,NOTURNO,32049,02:45:00,2.750000,00:19:00,0.316667,00:17:00,0.283333,11,12,9280,9.28,1,3.374545,0.843636
2908,2026-01-03,jan,3,sáb,11,NOTURNO,32051,03:05:00,3.083333,00:40:00,0.666667,00:25:00,0.416667,15,12,8460,8.46,1,2.743784,0.564000
2909,2026-01-03,jan,3,sáb,21,NOTURNO,33048,04:11:00,4.183333,00:33:00,0.550000,00:09:00,0.150000,29,15,6590,6.59,1,1.575299,0.227241

In [1]:
import funcs as fc

In [3]:
fc.serie_historica("producao", "20/05/2025", "20/06/2025", ["DIURNO"], ["seg","qua","sex"])

c:\Users\Felipe\Documents\projetos_python\monitoramento\funcs.py:61: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data_ini = pd.to_datetime(data_ini)
c:\Users\Felipe\Documents\projetos_python\monitoramento\funcs.py:62: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data_fin = pd.to_datetime(data_fin)

In [3]:
fc.medias("producao", "20/05/2025", "20/06/2025", ["DIURNO"], ["seg","qua","sex"])

c:\Users\Felipe\Documents\projetos_python\monitoramento\funcs.py:77: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data_ini = pd.to_datetime(data_ini)
c:\Users\Felipe\Documents\projetos_python\monitoramento\funcs.py:78: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data_fin = pd.to_datetime(data_fin)

In [2]:
fc.histograma("km_coleta", "horas_coleta", "20/05/2025", "20/08/2025", ["seg","ter"], ["NOTURNO"], [5,6])

c:\Users\Felipe\Documents\projetos_python\monitoramento\funcs.py:131: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data_ini = pd.to_datetime(data_ini)
c:\Users\Felipe\Documents\projetos_python\monitoramento\funcs.py:132: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data_fin = pd.to_datetime(data_fin)

In [2]:
df = pd.read_csv("dados.csv")

NameError: name 'pd' is not defined

In [10]:
teste = df.groupby(by = ["data", "setor"], as_index = False).aggregate(x = ("km_coleta","sum"),
                                                                       y = ("horas_coleta", "sum"))

In [15]:
np.polyfit(teste["x"], teste["y"], 1)
np.corrcoef(teste["x"], teste["y"])

array([[1.       , 0.4302886],
       [0.4302886, 1.       ]])

In [19]:
round(np.corrcoef(teste["x"], teste["y"])[0][1],3)

np.float64(0.43)

In [55]:
def histograma(variavel1, variavel2, data_ini, data_fin, dia_semana, turno, setor):
    dados = pd.read_csv("https://raw.githubusercontent.com/Schummy07/monitoramento/main/dados.csv")
    dados["data"] = pd.to_datetime(dados["data"])
    
    data_ini = pd.to_datetime(data_ini)
    data_fin = pd.to_datetime(data_fin)
    
    dados_filtro = dados[(dados["data"] >= data_ini) 
                   & (dados["data"]<= data_fin) 
                   & (dados["dia_semana"].isin(dia_semana))
                   & (dados["turno"].isin(turno))
                   & (dados["setor"].isin(setor))]
    
    for i in dados_filtro:
        if len(dados_filtro[i]) == 0:
            figura = go.Figure()
            figura.add_annotation(xref = "paper",
                                  yref = "paper",
                                  x = 0.5, y = 0.5,
                                  text = "não há valores correspondentes para o filtro selecionado")
            
            return figura
    
    dados_grafico = dados_filtro.groupby(by = ["data", "setor"], as_index = False).aggregate(x = (variavel1,"sum"),
                                                                                             y = (variavel2, "sum"))
    
    x = dados_grafico["x"]
    y = dados_grafico["y"]
    coefs = np.polyfit(x, y, 1)
    pred = coefs[0]*x + coefs[1]
    residuo = np.abs(dados_grafico["y"] - pred)
    
    figura = go.Figure()
    figura.add_trace(go.Histogram(x = residuo,  name = "Residuo"))
    
    return figura

In [58]:
histograma("km_coleta", "horas_coleta", "20/01/2024", "20/02/2025", ["seg","ter"], ["NOTURNO"], [5,6])

C:\Users\Felipe\AppData\Local\Temp\ipykernel_3640\3640190179.py:5: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data_ini = pd.to_datetime(data_ini)
C:\Users\Felipe\AppData\Local\Temp\ipykernel_3640\3640190179.py:6: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data_fin = pd.to_datetime(data_fin)

In [39]:
tente = dados[(dados["data"] >= "20/05/2025") 
                   & (dados["data"]<= "20/06/2025") 
                   & (dados["dia_semana"].isin(["seg"]))
                   & (dados["turno"].isin(["NOTURNO"]))
                   & (dados["setor"].isin([3,4,5,21]))]

In [49]:
dados["data"] = pd.to_datetime(dados["data"])
tente = dados[dados["data"] <=pd.to_datetime("20/01/2025")]

C:\Users\Felipe\AppData\Local\Temp\ipykernel_3640\905319812.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  tente = dados[dados["data"] <=pd.to_datetime("20/01/2025")]

In [27]:
import pandas as pd 
import numpy as np 
import plotly.express as plt

In [14]:
data = pd.read_csv("https://raw.githubusercontent.com/Schummy07/monitoramento/refs/heads/main/dados.csv")
data["data"] = pd.to_datetime(data["data"], format="ISO8601")
data.columns

Index(['data', 'mês', 'dia_mes', 'dia_semana', 'setor', 'turno', 'carro',
       'tempo_coleta', 'horas_coleta', 'tempo_trajeto', 'horas_trajeto',
       'tempo_aterro', 'horas_aterro', 'km_coleta', 'km_trajeto', 'producao',
       'producao_ton', 'viagens', 'ton/h', 'ton/km'],
      dtype='str')

In [32]:
def func_ajuste(data_ini, data_fin, variavel):
    data = pd.read_csv("https://raw.githubusercontent.com/Schummy07/monitoramento/refs/heads/main/dados.csv")
    data["data"] = pd.to_datetime(data["data"], format="ISO8601")
    
    if variavel == "ton/h" or variavel == "ton/km":
        dataset = data.groupby(["data","setor"], as_index = False)[variavel].mean()
    else:
        dataset = data.groupby(["data","setor"], as_index = False)[variavel].mean()
        
    final = dataset[(dataset["data"]>= data_ini) & (dataset["data"]<= data_fin)]
    
    return final

In [35]:
teste = func_ajuste("2025-04-10", "2026-08-05","ton/km")

In [37]:
plt.line(teste, x = "data", y = "ton/km", color = "setor")